//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Biblioteca.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIBLIOTECAEntities : DbContext
    {
        public BIBLIOTECAEntities()
            : base("name=BIBLIOTECAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBALUNO> TBALUNO { get; set; }
        public virtual DbSet<TBEDITORA> TBEDITORA { get; set; }
        public virtual DbSet<TBEMPRESTIMO> TBEMPRESTIMO { get; set; }
        public virtual DbSet<TBFUNCIONARIO> TBFUNCIONARIO { get; set; }
        public virtual DbSet<TBITEMEMPRESTIMO> TBITEMEMPRESTIMO { get; set; }
        public virtual DbSet<TBLIVRO> TBLIVRO { get; set; }
        public virtual DbSet<TBPERIODICO> TBPERIODICO { get; set; }
    }
}
