//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Biblioteca.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBEMPRESTIMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBEMPRESTIMO()
        {
            this.TBITEMEMPRESTIMO = new HashSet<TBITEMEMPRESTIMO>();
        }
    
        public int IDEMPRESTIMO { get; set; }
        public Nullable<int> IDALUNO { get; set; }
        public Nullable<int> IDFUNCIONARIO { get; set; }
        public Nullable<System.DateTime> HORA { get; set; }
        public Nullable<System.DateTime> DEVOLUCAO { get; set; }
    
        public virtual TBALUNO TBALUNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBITEMEMPRESTIMO> TBITEMEMPRESTIMO { get; set; }
        public virtual TBFUNCIONARIO TBFUNCIONARIO { get; set; }
    }
}
