//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Biblioteca.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLIVRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLIVRO()
        {
            this.TBITEMEMPRESTIMO = new HashSet<TBITEMEMPRESTIMO>();
        }
    
        public int IDLIVRO { get; set; }
        public Nullable<int> IDEDITORA { get; set; }
        public string NOME { get; set; }
        public string ASSUNTO { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string AUTOR { get; set; }
    
        public virtual TBEDITORA TBEDITORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBITEMEMPRESTIMO> TBITEMEMPRESTIMO { get; set; }
    }
}
